#define SECOND 1000
#define CABINLIGHTINTERVAL 10
#define CHAIRDETECTTIME 3
#define CHAIRNOTDETECTTIME 10
#define HEARTBEATDETECTTIME 3
#define MEDITATIONNODETECTTIME 5

#define SPEAKERLOOPCOUNT 5
#define SPEAKERLOOPCOUNTMINUSONE 4

#define ENDNOPRESSURE 10
#define ENDPRESSUREDETECTED 60