#include "Arduino.h"
#define SECOND 1000

//CABIN LIGHT ON 
#define CABINLIGHTINTERVAL 10
#define CHAIRDETECTTIME 3


#define CHAIRNOTDETECTTIME 10
#define HEARTBEATDETECTTIME 3
#define MEDITATIONNODETECTTIME 5
#define FIDGETDETECTTIME 5

#define SPEAKERLOOPCOUNT 5
#define SPEAKERLOOPCOUNTMINUSONE 4

#define ENDNOPRESSURE 10
#define ENDPRESSUREDETECTED 60



//SPEAKER CONSTANTS
#define SPEAKER1SERIAL Serial1
#define SPEAKER2SERIAL Serial2
#define SPEAKER2STARTVOL 10
#define SPEAKER2MAXVOLUME 30

// PIR SENSOR
#define PIRPIN 20

// BLUETOOTH RX TX
#define BTRXPIN 10
#define BTTXPIN 11

// PRESSURE SENSOR
#define PRESSUREPIN 36
#define PRESSUREHIGH 500

// LIGHT PWM PINS
#define LIGHTFRONT 10
#define LIGHTLEFT 11
#define LIGHTRIGHT 12
#define LIGHTBACK 13
#define MAXLIGHT 150
#define MINLIGHT 0
#define LOWLIGHT 50

// HEARTBEAT 
#define AVGHEARTBEAT 60

// DIFFUSER PIN
#define DIFFUSERPIN 34





