#include "Arduino.h"
#define SECOND 1000

// Meditation flow check state
#define MEDITATIONFLOWCHECKSTATEGLIMMER 2000

// HEART RATE SENSOR ANALOG
#define HEARTRATESENSOR 21

// BLUETOOTH RX AND TX
#define BTRXPIN 10
#define BTTXPIN 11

// LED RING
#define LEDPIN 2
#define NUMLEDS 12
#define MAXBRIGHTNESS 60

// BUZZER
#define BUZZERPIN 8
#define BUZZERINTERVAL 1000
