#include "Arduino.h"
#define SECOND 1000

#define MEDITATIONFLOWCHECKSTATEGLIMMER 2000

// HEART RATE SENSOR
#define HEARTRATESENSOR 21

// BLUETOOTH RX AND TX
#define BTRXPIN 10
#define BTTXPIN 11

// LED RING
#define LEDPIN 2
#define NUMLEDS 12
#define MAXBRIGHTNESS 60