#include "Arduino.h"
#define SECOND 1000

// Meditation flow check state
#define MEDITATIONFLOWCHECKSTATEGLIMMER 2000

// HEART RATE SENSOR ANALOG
#define HEARTRATESENSOR A1
#define BEATINTERVAL 300
#define BEATINTERVALHALF 150
#define VALIDHIGH 890
#define VALIDLOW 850
#define HRTHRESHOLD 869
#define HRMININTERVAL 450
#define RECALIBRATIONINTERVAL 30000

// MOTION SENSOR
#define MOTIONTHRESHOLD 3
#define MOTIONDETECTDURATION 30

// LED RING
#define LEDPIN 2
#define NUMLEDS 12
#define MAXBRIGHTNESS 40

// BUZZER
#define BUZZERPIN 9
#define BUZZERINTERVAL 1000
#define BUZZERPOWER 200 // range 80 - 255

// COLOURS FOR EACH STAGE
#define MEDITATIONFLOWLIGHT 0x3333ff
#define MEDITATIONLIGHT 0x33ff33
#define MEDITATIONLIGHTNOHB 0xff3333